/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_facebook_FacebookJNIHelper */

#ifndef _com_game_facebook_FacebookJNIHelper
#define _com_game_facebook_FacebookJNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_facebook_FacebookJNIHelper
 * Method:    nativeOnLoginSuccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_facebook_FacebookJNIHelper_nativeOnLoginSuccess
  (JNIEnv *, jclass);

/*
 * Class:     com_game_facebook_FacebookJNIHelper
 * Method:    nativeOnLoginFailed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_facebook_FacebookJNIHelper_nativeOnLoginFailed
  (JNIEnv *, jclass);

/*
 * Class:     com_game_facebook_FacebookJNIHelper
 * Method:    nativeOnSessionClosed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_facebook_FacebookJNIHelper_nativeOnSessionClosed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
